practice_query_builder laravel
st-tuansu/laravel-intern-2111 pull request #2
Opened 2021-12-21 11:56 UTC by st-tuansu

2021-12-22 02:23 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $tasks = json_decode($data, true);
Chỗ này em không cần parse ra array, để vậy truyền qua view, bên view foreach rồi lấy $value->column_name là được.

2021-12-22 02:23 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
>          return view('admin.tasks.store', compact('result'));
Chỗ này redirect về trang create,  sử dụng flash messages.
return back()->with('success', 'Task created successfully!');
Bên view kiểm tra Session::has('success') rồi show message.

2021-12-22 02:39 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +            ->get();
dùng first();

2021-12-22 02:45 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +            ->get();
dùng first();

2021-12-22 02:50 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        return view('admin.tasks.update', compact('data', 'id'));
return back(),  sử dụng flash messages tương tự ở trên

2021-12-22 03:12 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +            return view('admin.tasks.destroy', compact('result', 'id'));
Bên view ko thấy dùng $result, chỗ này ko cần tạo 1 view destroy, nên redirect về lại trang index kèm theo flash message

2021-12-22 03:20 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $data1 = DB::table('users')->select('users.name')->where('id', 1)->get(); //Lấy ra một dữ liệu trong table.
dùng first();

2021-12-22 03:29 UTC, st-trampham reviewed
please check my comments, thanks!

2021-12-22 03:34 UTC, st-minhdao requested changes

2021-12-22 03:34 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $data = $request->all();
em có thể dùng luôn biến $request mà, đâu cần tạo ra biến data làm gì
hoặc dùng `$data = $request->validated();` để lấy ra những cột mình đã khai báo trong request và gắn vào hàm insert luôn cũng được

2021-12-22 03:34 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +            ->insertGetId(array(
tạo biến $result nhưng ko dùng
insertGetID cũng ko thấy dùng đến ID

2021-12-22 03:34 UTC, st-minhdao commented on layout_and_module_task/database/migrations/2021_12_20_062623_create_tasks_table.php
> +            $table->integer('status');
dùng kiểu dữ liệu nhỏ hơn, và là số dương

2021-12-22 03:43 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/edit.blade.php
> +                    <td><input type="text" name="assignee" class="form-control form-control-user" id="assignee"
Chỗ này dùng select tag để chọn user, kiểm tra lại luôn view create

2021-12-22 05:23 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/index.blade.php
>                                  class="btn btn-warning btn-circle btn-sm"><i class="far fa-edit"></i></a>
move các tag show, edit ra khỏi form

2021-12-22 07:31 UTC, st-tuansu commented on layout_and_module_task/database/migrations/2021_12_20_062623_create_tasks_table.php
> +            $table->integer('status');
dạ để em fix lại

2021-12-22 07:31 UTC, st-tuansu commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $data1 = DB::table('users')->select('users.name')->where('id', 1)->get(); //Lấy ra một dữ liệu trong table.
dạ để em fix lại

2021-12-23 02:18 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
>      }
Thêm space

2021-12-23 02:21 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        return view('admin.tasks.edit', compact('task','id'));
Trong `task` có id task rồi nên ko cần truyền id qua nữa
Không cần join với bảng users chỗ này, bên view edit chỗ assignee sẽ là select tag chọn 1 user trong list user

2021-12-23 02:26 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/create.blade.php
> +                        @foreach ($users as $key)
thay tên biến`$key` thành `$value` hoặc `$user` cho hợp lí

2021-12-23 02:34 UTC, st-tuansu commented on layout_and_module_task/resources/views/admin/tasks/create.blade.php
> +                        @foreach ($users as $key)
oke chị

2021-12-23 03:23 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/create.blade.php
> +                            <option value="{{ $uer->id }}" selected="selected">{{ $user->name }}</option>
$user->id

2021-12-23 03:27 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/edit.blade.php
> +                            <option value="{{ $task->assignee }}" selected="selected">{{ $user->name }}</option>
value ở đây là lấy $user->id
Kiểm tra nếu $task->assignee == $user->id thì add selected attribute

2021-12-23 03:28 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/index.blade.php
> +            @foreach ($tasks as $key)
đổi tên biến $key thành $task hoặc $value

2021-12-23 03:28 UTC, st-tuansu commented on layout_and_module_task/resources/views/admin/tasks/create.blade.php
> +                            <option value="{{ $uer->id }}" selected="selected">{{ $user->name }}</option>
dạ đã fix rồi chị

2021-12-23 03:31 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +            ->where('tasks.id', $id)
where id dc rồi, không cần tasks.id

2021-12-23 04:56 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/create.blade.php
> +                    <select multiple="true" name="assignee" id="assignee" class="form-control select2">
remove `multiple="true"`

2021-12-23 04:57 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/create.blade.php
> +                            <option value="{{ $user->id }}" selected="selected">{{ $user->name }}</option>
remove `selected="selected"`

2021-12-23 04:57 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/edit.blade.php
> +                    <select multiple="true" name="assignee" id="assignee" class="form-control select2">
remove `multiple="true"`

2021-12-23 04:58 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/edit.blade.php
> +                            <option value="{{ $user->id }}" @if($task->assignee == $user->id) selected @endif}}>{{ $user->name }}</option>
dư `}}` chỗ endif

2021-12-23 07:00 UTC, st-trampham commented
LGTM!

2021-12-23 13:50 UTC, merged